### ISSUE TITLE
Subscription does not working

### ISSUE THREAD

**Issue by danny920825** [jadolg/shadowmere#220]
Im try it using this url **[https://shadowmere.akiel.dev/api/sub](https://shadowmere.akiel.dev/api/sub)** to ShadowSocks and **[https://shadowmere.akiel.dev/api/b64sub/](https://shadowmere.akiel.dev/api/b64sub/)** to V2Ray and nothing happens

**Comment by jadolg** [comment]
Both [Nekoray](https://github.com/MatsuriDayo/nekoray) and [Matsuri](https://play.google.com/store/apps/details?id=moe.matsuri.lite) work fine with https://shadowmere.akiel.dev/api/b64sub/ 
And the "default" [Shadowsocks app](https://play.google.com/store/apps/details?id=com.github.shadowsocks) works just fine with  https://shadowmere.akiel.dev/api/sub
It seems there are issues with [v2rayng](https://play.google.com/store/apps/details?id=com.v2ray.ang) and the way they poll for subscriptions.
AFAIK, the standard has not changed (base64 encoded list of addresses) 
My recommendation: Use Matsuri while it gets sorted out.
