### ISSUE TITLE
Add option to filter by port

### ISSUE THREAD

**Issue by samthelion17** [jadolg/shadowmere#38]
Sometimes we can only use 443 to connect to this servers...

**Comment by jadolg** [comment]
I'm adding backend capabilities for this here https://github.com/jadolg/shadowmere/pull/39
Then the frontend needs to be modified

**Comment by jadolg** [comment]
This is solved on the backend side.
I created an issue (https://github.com/swordfest/shadowmere/issues/4) for the frontend and let @swordfest know

**Comment by samthelion17** [comment]
Great! This will (not literally) save my life. I'll start using the API while @swordfest gets the frontend ready. Shall this issue be closed? If not, re-open it plz!
