### ISSUE TITLE
Add Flags in the Subscription

### ISSUE THREAD

**Issue by rakitanc** [jadolg/shadowmere#98]
Helps in identifying from the huge list

**Comment by jadolg** [comment]
Do you know the encoding for these flags? I can't figure out how to translate from country code to flag.

**Comment by rakitanc** [comment]
> Do you know the encoding for these flags? I can't figure out how to translate from country code to flag.

I am a basic user So can't help with technicality but these might help you

https://mdbootstrap.com/docs/standard/content-styles/flags/
https://flagicons.lipis.dev/
https://andycroll.com/ruby/convert-iso-country-code-to-emoji-flag/

**Comment by jadolg** [comment]
That gave me a good idea. I found a library that should do it and I'm going to try it https://github.com/jadolg/shadowmere/pull/110

**Comment by jadolg** [comment]
![image](https://user-images.githubusercontent.com/5427672/214322498-0e03f7a1-67bc-4ffe-942c-3e202a1fbeb7.png)
